// const BASE_URL = ''
const BASE_URL = 'https://yeji-j.github.io/yeji.log'
const titleData = {
  canada: {
    vancouver: {
      20190621: {
        title: `밴쿠버 훈제 연어는 생각만해도 침이 고인다`,
      },
    },
  },
  japan: {
    fukuoka: {
      20180814: {
        title: `무계획 여행은 J에게 조금 힘들었다`,
      },
    },
    tokyo: {
      20170617: {
        title: `TOKYO`,
      },
    },
    osaka: {
      20181201: {
        title: `OSAKA`,
      },
    },
  },
  taiwan: {
    taipei: {
      20191213: {
        title: `이 여행을 계기로 중국어를 배우게 됐다`,
      },
      20221129: {
        title: `조금은 외로웠지만 많은 것을 채워 돌아왔다`,
      },
    },
    kaohsiung: {
      20230612: {
        title: `막연히 두려웠던 취준을 시작하기 전 떠났던 여행`,
      },
    },
    taichung: {
      20240216: {
        title: `엄마는 대만에서 살고 싶다고 했다`,
      },
    },
  },
  vietnam: {
    hochiminh: {
      20220605: {
        title: `모든 순간이 마음 편하고 좋았던 호치민`,
      },
    },
    nhatrang: {
      20230709: {
        title: `가족 여행은 심사숙고 하는 게 좋다`,
      },
    },
  },
  thailand: {
    bangkok: {
      20240614: {
        title: `이로써 세 명만 아는 비밀이 더 늘어났다`,
      },
    },
  },
  usa: {
    lasvegas: {
      20190422: {
        title: `자연의 숭고함에 압도 당한 날`,
      },
    },
    losangeles: {
      20190224: {
        title: `LA`,
      },
      20190609: {
        title: `엄마와 함께한 가장 좋았던 드라이브`,
      },
    },
    newyork: {
      20190626: {
        title: `여름 뉴욕은 지하철 악취가 심하다`,
      },
    },
    sandiego: {
      20190110: {
        title: `샌디에고를 통해 맛본 캘리포니아의 첫인상은 따뜻하고 여유로웠다`,
      },
    },
    sanfrancisco: {
      20190419: {
        title: `사랑하는 사람과 꼭 같이 오고 싶은 레스토랑이 생겼다`,
      },
      20190613: {
        title: `우중충한 샌프란 날씨를 따뜻한 클램 차우더로 이겨냈다`,
      },
    },
    seattle: {
      20190616: {
        title: `백인밖에 없었던 퀸즈 거리, 약간은 기괴했다`,
      },
    },
  },
  singapore: {
    singapore: {
      20170717: {
        title: `5년 만에 다시 찾은 싱가폴은 여전히 깨끗하고 아름답다`,
      },
    },
  },
}

const photoData = {
  canada: {
    vancouver: {
      20190621: [
        {
          img: `${BASE_URL}/canada/vancouver/2019-06-21/breakfast.jpg`,
          date: `2019-06-21`,
          country: `Canada`,
          city: `Vancouver`,
          title: `BREAKFAST`,
          desc: `캐나다에서 엄마가 만들어준 조식`,
          tags: [],
        },
      ],
    },
  },
  japan: {
    fukuoka: {
      20180814: [
        {
          img: `${BASE_URL}/japan/fukuoka/2018-08-14/brunch.jpg`,
          date: `2018-08-14`,
          country: `Japan`,
          city: `Fukuoka`,
          title: `BRUNCH`,
          desc: ``,
          tags: [],
        },
      ],
    },
    tokyo: {
      20170617: [
        {
          img: `${BASE_URL}/japan/tokyo/2017-06-17/tokyotower.jpg`,
          date: `2017-06-17`,
          country: `Japan`,
          city: `Tokyo`,
          title: `TOKYO TOWER`,
          desc: ``,
          tags: [],
        },
      ],
    },
    osaka: {
      20181201: [
        {
          img: `${BASE_URL}/japan/osaka/2018-12-01/yakiniku.jpeg`,
          date: `2018-12-01`,
          country: `Japan`,
          title: `YAKI NIKU`,
          city: `Osaka`,
          desc: ``,
          tags: [],
        },
      ],
    },
  },
  taiwan: {
    taipei: {
      20191213: [
        {
          img: `${BASE_URL}/taiwan/taipei/2019-12-13/jiufen.jpg`,
          date: `2019-12-13`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `Spirited Away`,
          desc: ``,
          tags: [],
        },
      ],
      20221129: [
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/tofu.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `EGG TOFU`,
          desc: `혼여행의 단점은 \n 다양한 음식을 맛보지 못한다는 것이다`,
          tags: [`FAVS`, `food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/coin.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `airport train`,
          desc: `하루만에 계획하고 떠난 여행`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/noodle.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `mala noodle`,
          desc: `타이베이 도착 후 첫 끼 \n 선지가 정말 부드러웠다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/milk.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `milk`,
          desc: `귀여운 병에 담겨 나온 우유 \n 그냥 기분이 좋아졌다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/post.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `post`,
          desc: `카페 한 구석에 모여 있던 것들 \n 한 장씩 읽는 재미가 있다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/coffee.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `smile cookie`,
          desc: `맛은 꽤나 평범했던 쿠키 \n 누군가를 닮았다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/fried.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `yansuji`,
          desc: `숙소 가는 길에 들렸던 옌수지 가게 \n 몰랐는데 유명한 집이었다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/dumpling.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `yum`,
          desc: `한 입 거리 만두 \n 귀여워라`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/flower.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `chiapei lin`,
          desc: `차페이 언니를 위해 꽃을 샀다 \n 3년 만이라 떨렸다`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/huoguo.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `roommate reunion`,
          desc: `언니가 사준 훠궈 \n 중국어 한국어 영어를 섞어가며 \n 따뜻하고 재밌었던 대화`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/greenlight.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `greenlight`,
          desc: `대만은 신호등까지 귀엽다 \n 싫은 것을 찾는 게 더 힘들다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/taipei/2022-11-29/haohaochi.jpg`,
          date: `2022-11-29`,
          country: `Taiwan`,
          city: `Taipei`,
          title: `wonton mien`,
          desc: `한국으로 돌아가기 전 먹은 완탕면 \n 하오하오츠인 가게명과 \n 정반대의 맛이다`,
          tags: [`food`],
        },
      ],
    },
    kaohsiung: {
      20230612: [
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/tea.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `pineapple bread`,
          desc: `가오슝 써니힐은 \n 차와 펑리수를 무료로 제공한다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/bus.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `space out`,
          desc: `창 밖을 보며 멍을 때리다 \n 한 정거장을 일찍 내렸다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/huoguo.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `huo guo`,
          desc: `두 다리를 모기에게 내어주고 \n 마침내 먹은 훠궈`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/carrefour.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `carrefour`,
          desc: `야경이 예뻤던 까르푸 건물`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/dumpling.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `cute baozhi`,
          desc: `아침을 먹으러 가던 중 \n 옹기종기 모여있는 빠오즈를 \n 그냥 지나칠 수 없었다`,
          tags: [`FAVS`, `food`],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/papaya.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `papaya juice`,
          desc: `처음 먹어봤던 파파야 주스 \n 달달한 고구마 맛이 난다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/ikea.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `ikea`,
          desc: `숙소로 걸어가는 길에 \n 괜히 예뻤던 이케아`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/fishcake.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `fish cake`,
          desc: `소류구 가는 배를 타기 전 \n 갓 튀긴 어묵을 모른척할 수 없었다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/liuqiu.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `liuqiu`,
          desc: `비가 왔지만 바닷속은 고요했다 \n 다음엔 오래 머무르고 싶다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/noodle.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `taiwanese noodle`,
          desc: `부드러웠던 족발 국수 \n 다진 마늘을 넣으면 더 맛있다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/kaohsiung/2023-06-12/donut.jpg`,
          date: `2023-06-12`,
          country: `Taiwan`,
          city: `Kaohsiung`,
          title: `taiwanese street donut`,
          desc: `땡볕에서 20분 줄을 섰던 도너츠 \n 땅콩과 깨가 고소했다`,
          tags: [`food`],
        },
      ],
    },
    taichung: {
      20240216: [
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/chunshuitang.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `original milk tea`,
          desc: `밀크티 원조 본점 \n 엄마는 흑당 흑임자 인절미를 좋아했다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/waiting.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `for breakfast`,
          desc: `아침을 주문하고 기다리던 중에`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/noodle.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `mala noodle`,
          desc: `엄마가 우연히 발견한 국수 맛집`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/view.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `on our way to xinwuri`,
          desc: `기차를 타고 가며 봤던 풍경 \n 평온하다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/rice.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `din tai feng`,
          desc: `딘타이펑의 모든 메뉴는 실패가 없다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/mom.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `best friend`,
          desc: `최고의 여행 메이트`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/danbing.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `DAN BING`,
          desc: `대만 대표 아침 메뉴, 딴삥`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/huoguo.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `taiwanese hot pot`,
          desc: `야무지게 소스도 만들어 먹는 엄마`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/coffe.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `salt coffee`,
          desc: `85도씨 소금 커피`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/accom.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `06:00am`,
          desc: `새벽에 일어나 성경을 읽던 엄마 \n 마음이 편안하다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/taiwan/taichung/2024-02-16/pork.jpg`,
          date: `2024-02-16`,
          country: `Taiwan`,
          city: `Taichung`,
          title: `dongporou`,
          desc: `타이중을 떠나기 전 먹었던 동파육 \n 엄마도 좋아했다`,
          tags: [`food`],
        },
      ],
    },
  },
  vietnam: {
    hochiminh: {
      20220605: [
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/comtam.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `Com Tam`,
          desc: `베트남식 갈비 덮밥 \n 지금도 생각나요`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/hangry.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `hangry`,
          desc: `베트남 도착 후 첫 끼 \n 도저히 먹을 수가 없었다 \n 내 앞 사람은 비명을 질렀다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/fruits.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `vietnam fruits`,
          desc: `모든 종류의 망고와 과일 \n 누군가의 향수를 부르는 마일로 초코 우유 \n 처음 먹어봤던 두리안`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/buncha.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `bun cha`,
          desc: `배불러도 들어가던 분짜`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/crocs.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `crocs night`,
          desc: `흰색 크록스를 찾아 헤매던 밤`,
          tags: [],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/crab.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `soft shell crab`,
          desc: `토마토도 안 보이는 맛`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/noodle.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `crab noodle`,
          desc: `국물까지 싹싹 비웠다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/pool.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `to the moon and back`,
          desc: `마음 꽉차게 행복했던 아침 수영`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/pizza.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `salty salty`,
          desc: `소금 덩어리 피자 \n 재밌게 먹었다`,
          tags: [`food`],
        },

        {
          img: `${BASE_URL}/vietnam/hochiminh/2022-06-05/corona.jpg`,
          date: `2022-06-05`,
          country: `Vietnam`,
          city: `Ho Chi Minh`,
          title: `covid-19`,
          desc: `코로나를 뚫고 다녀온 여행 \n 우린 강했다`,
          tags: [],
        },
      ],
    },
    nhatrang: {
      20230709: [
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/pool.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `Nha trang`,
          desc: `나트랑의 풍경은 참 청미하다 \n 라고 에어컨을 쐬며 생각했다`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/passport.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `run yeji run`,
          desc: `예지야 도망쳐 \n 늦지 않았어`,
          tags: [],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/banxeo.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `ban xeo`,
          desc: `까탈 공주들에게 \n 첫 끼는 합격이었다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/cross.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `church`,
          desc: `억지로 기부금을 내라던 경비원 \n donation이 강도라는 뜻이었을까`,
          tags: [],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/church.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `amen`,
          desc: `밖이 너무 더워서 기도하는 척 했다 \n 하나님 죄송해요`,
          tags: [],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/food.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `spring roll`,
          desc: `목에 구내염이 생겨서 \n 사포를 넘기는 것 같았다 \n 맛은 좋았다`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/view.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `sunset`,
          desc: `해가 질 때까지 \n 해먹에 누워 있었다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/rain.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `rainy night`,
          desc: `갑작스런 스콜에 \n 식당에서 비닐봉지를 빌렸다 \n 모두가 자지러졌다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/vietnam/nhatrang/2023-07-09/inhwa.jpg`,
          date: `2023-07-09`,
          country: `Vietnam`,
          city: `Nha trang`,
          title: `well done`,
          desc: `인생 첫 다래끼를 얻은 여행 \n 정예지 잘 견뎠다 \n 귀여운 인화로 마무리`,
          tags: [],
        },
      ],
    },
  },
  thailand: {
    bangkok: {
      20240614: [
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/curry.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `crab curry`,
          desc: `태국 음식에 반해버린 순간`,
          tags: [`FAVS`, `FOOD`],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/film.jpeg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `best cut`,
          desc: `얼굴이 나오지 않아 베스트 컷이 됐다`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/pool.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `Pool`,
          desc: `더 예쁜 발이 혜진언니다 \n어느 쪽일까요`,
          tags: [],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/noodle.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `fried noodle`,
          desc: `정예지 메뉴 선택 참 잘 해`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/bus.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `bus`,
          desc: `강한 자들만 살아 남는 태국 버스 \n우린 결국 내렸다`,
          tags: [],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/bhlee.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `bh at his best`,
          desc: `열사병 걸리기 전 잔뜩 겁먹은 모습`,
          tags: [],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/mukata.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `mukata`,
          desc: `땀 뻘뻘 흘리며 먹었던 태국 대표 음식`,
          tags: [`FOOD`],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/jazzbar.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `jazz bar`,
          desc: `다시 피아노를 시작하고 싶었던 날`,
          tags: [`FAVS`],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/fries.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: `heart shaped ketchup`,
          desc: `케찹마저 내 스타일`,
          tags: [`food`],
        },
        {
          img: `${BASE_URL}/thailand/bangkok/2024-06-14/bin.jpg`,
          date: `2024-06-14`,
          country: `Thailand`,
          city: `Bangkok`,
          title: 'trash bin',
          desc: `태국 맥도날드 쓰레기통`,
          tags: [],
        },
      ],
    },
  },
  usa: {
    lasvegas: {
      20190422: [
        {
          img: `${BASE_URL}/usa/lasvegas/2019-04-22/grandcanyon.jpg`,
          date: `2019-04-22`,
          country: `USA`,
          city: `Las Vegas`,
          title: `grand canyon`,
          desc: ``,
          tags: [],
        },
      ],
    },
    losangeles: {
      20190224: [
        {
          img: `${BASE_URL}/usa/losangeles/2019-02-24/pinkwall.jpg`,
          date: `2019-02-24`,
          country: `USA`,
          city: `Los Angeles`,
          title: `pink wall`,
          desc: ``,
          tags: [],
        },
      ],
      20190609: [
        {
          img: `${BASE_URL}/usa/losangeles/2019-06-09/urbanlight.jpg`,
          date: `2019-06-09`,
          country: `USA`,
          city: `Los Angeles`,
          title: `urban light`,

          desc: ``,
          tags: [],
        },
      ],
    },
    newyork: {
      20190626: [
        {
          img: `${BASE_URL}/usa/newyork/2019-06-26/chelsea.jpg`,
          date: `2019-06-26`,
          country: `USA`,
          city: `New York`,
          title: `chelsea market`,
          desc: ``,
          tags: [],
        },
      ],
    },
    sandiego: {
      20190110: [
        {
          img: `${BASE_URL}/usa/sandiego/2019-01-10/harborhouse.jpg`,
          date: `2019-01-10`,
          country: `USA`,
          city: `San Diego`,
          title: `harbor house`,
          desc: ``,
          tags: [],
        },
      ],
    },
    sanfrancisco: {
      20190419: [
        {
          img: `${BASE_URL}/usa/sanfrancisco/2019-04-19/steak.jpg`,
          date: `2019-04-19`,
          country: `USA`,
          city: `San Francisco`,
          title: `house of prime rib`,
          desc: ``,
          tags: [`FAVS`, `FOOD`],
        },
      ],
      20190613: [
        {
          img: `${BASE_URL}/usa/sanfrancisco/2019-06-13/fisherman.jpg`,
          date: `2019-06-13`,
          country: `USA`,
          city: `San Francisco`,
          title: 'fisherman`s wharf',
          desc: ``,
          tags: [],
        },
      ],
    },
    seattle: {
      20190616: [
        {
          img: `${BASE_URL}/usa/seattle/2019-06-16/glassart.jpeg`,
          date: `2019-06-16`,
          country: `USA`,
          city: `Seattle`,
          title: `glass art`,
          desc: ``,
          tags: [],
        },
      ],
    },
  },
  singapore: {
    singapore: {
      20170717: [
        {
          img: `${BASE_URL}/singapore/2017-07-17/flower.jpg`,
          date: `2017-07-17`,
          country: `Singapore`,
          city: `Singapore`,
          title: `street flower shop`,
          desc: `5년 만에 다시 간 싱가폴은 여전히 아름답다`,
          tags: [`FAVS`],
        },
      ],
    },
  },
}

export default { photoData, titleData }
